@startuml
title Smart home Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the Smart Home system")
Person(admin, "Administrator", "An administrator managing the system")
System(SmartHomeSystem, "Smart home System", "System managing home devices")

Container_Boundary(SmartHomeSystem, "Smart home System") {
  Container(ApiGateway, "API Gateway", "Kong", "routes, balances")
  ContainerDb(Database, "Database", "PostgreSQL", "Stores users, device data, oauth tokens, scripts, partners, device types, partner device types, houses")
  Container(Cache, "Cache", "Redis", "Stores users, device data, oauth tokens, scripts, device types, partners, partner device types")
  Container(Auth, "Authentication Service", "Java, Spring", "Authenticates and authorizes user, OAuth with Partners")
  Container(WebDeviceApp, "Web Device App", "React/js", "Handles user's device requests, http")
  Container(MobileDeviceApp, "Mobile Device App", "Kotlin", "Provide limited subset of device functionality, http")
  Container(DeviceApp, "Device App", "Java, Spring", "Manages and monitors devices")
  Container(DeviceIntegration, "Device Partners Integrations", "Java, Spring", "Integrates with Partners")
'  Container(Queue, "Message Queue", "Kafka", "Stores events")
}

System_Ext(partner1Api, "Partner 1 API", "API for device management and monitoring")

'System_Ext(partner1QueueClient, "Partner 1 Queue Client", "Publish sensor events")

Rel(user, WebDeviceApp, "Uses the system via a browser")
Rel(user, MobileDeviceApp, "Uses the system via a mobile application")
Rel(admin, WebDeviceApp, "Uses the system via a browser")
Rel(admin, MobileDeviceApp, "Uses the system via a mobile application")
Rel(ApiGateway, Auth, "Authenticate and authorize the user")
Rel(WebDeviceApp, ApiGateway, "Sends device commands")
Rel(MobileDeviceApp, ApiGateway, "Sends device commands")
Rel(ApiGateway, DeviceApp, "Sends device commands")
Rel(Auth,Database,"Reads/Writes user, OAuth data")
Rel(Auth,DeviceIntegration,"OAuth authorizes")
Rel(DeviceIntegration,partner1Api,"OAuth authorizes, syncs the devices, sends the commands")
'Rel(partner1QueueClient,Queue,"Publish sensor events")
Rel(partner1Api, DeviceIntegration,"Send sensor events")
Rel(DeviceIntegration,Database,"Gets user device OAuth tokens")
'Rel(Queue,DeviceApp,"Receive sensor events")
Rel(DeviceApp,DeviceIntegration,"Sends the commands")
Rel(DeviceApp,Database,"Reads script and device data")
Rel(DeviceApp,Cache,"Reads script and device data")


@enduml